AWSTemplateFormatVersion: "2010-09-09"
Description: "An AWS Serverless Specification template describing your function."
Parameters:
  #alias :
    #Type : String
  version :
    Type : String
Resources: 
  SNSTopic1: 
    Type: "AWS::SNS::Topic"
  jithinaws: 
    Properties: 
      CodeUri: "s3://almrc/jithin_aws-3d50c3a8-ebdd-4207-ad2e-2a9b3852a871.zip"
      Description: ""
      AutoPublishAlias: prod
      #AutoPublishVersion: !Ref version
      Events: 
        SNS1: 
          Properties: 
            Topic: 
              Ref: SNSTopic1
          Type: SNS
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Version: !Ref version
      Role: "arn:aws:iam::543816070942:role/lambda_basic_execution"
      Runtime: python3.6
      Timeout: 3
    Type: "AWS::Serverless::Function"
Transform: "AWS::Serverless-2016-10-31"
#
